security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        MelbSymfony2\ForumExampleBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #in_memory:
        #    users:
        #        user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #        admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        default:
            entity: { class: MelbSymfony2\ForumExampleBundle\Entity\User, property: name }

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        login:
            pattern:  ^/session/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /session/login/check
                login_path: /session/login
            logout:
                path:   /session/logout
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: /user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /, roles: ROLE_USER }
